import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const sampleTransactions = [
        // User 1 (Aarav Sharma) - November 2024
        {
            userId: 1,
            amount: 4500.00,
            category: 'Salary',
            merchant: 'Tech Solutions Pvt Ltd',
            date: new Date('2024-11-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            userId: 1,
            amount: 450.00,
            category: 'Food & Dining',
            merchant: 'Dominos Pizza',
            date: new Date('2024-11-03').toISOString(),
            type: 'debit',
            description: 'Dinner with friends',
            createdAt: new Date('2024-11-03').toISOString(),
        },
        {
            userId: 1,
            amount: 280.00,
            category: 'Transportation',
            merchant: 'Uber',
            date: new Date('2024-11-05').toISOString(),
            type: 'debit',
            description: 'Ride to office',
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            userId: 1,
            amount: 1200.00,
            category: 'Utilities',
            merchant: 'Electricity Board',
            date: new Date('2024-11-07').toISOString(),
            type: 'debit',
            description: 'Monthly electricity bill',
            createdAt: new Date('2024-11-07').toISOString(),
        },
        {
            userId: 1,
            amount: 799.00,
            category: 'Entertainment',
            merchant: 'Netflix',
            date: new Date('2024-11-10').toISOString(),
            type: 'debit',
            description: 'Premium subscription',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 1,
            amount: 650.00,
            category: 'Food & Dining',
            merchant: 'Starbucks',
            date: new Date('2024-11-12').toISOString(),
            type: 'debit',
            description: 'Coffee and snacks',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 1,
            amount: 15000.00,
            category: 'Electronics',
            merchant: 'Amazon India',
            date: new Date('2024-11-15').toISOString(),
            type: 'debit',
            description: 'New smartphone purchase',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 1,
            amount: 500.00,
            category: 'Healthcare',
            merchant: 'Apollo Pharmacy',
            date: new Date('2024-11-18').toISOString(),
            type: 'debit',
            description: 'Monthly medicines',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 1,
            amount: 850.00,
            category: 'Transportation',
            merchant: 'Indian Oil',
            date: new Date('2024-11-20').toISOString(),
            type: 'debit',
            description: 'Fuel refill',
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            userId: 1,
            amount: 1200.00,
            category: 'Investment',
            merchant: 'Mutual Fund Returns',
            date: new Date('2024-11-25').toISOString(),
            type: 'credit',
            description: 'Monthly SIP returns',
            createdAt: new Date('2024-11-25').toISOString(),
        },
        
        // User 1 (Aarav Sharma) - December 2024
        {
            userId: 1,
            amount: 4500.00,
            category: 'Salary',
            merchant: 'Tech Solutions Pvt Ltd',
            date: new Date('2024-12-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            userId: 1,
            amount: 2500.00,
            category: 'Food & Dining',
            merchant: 'Barbeque Nation',
            date: new Date('2024-12-05').toISOString(),
            type: 'debit',
            description: 'Birthday celebration',
            createdAt: new Date('2024-12-05').toISOString(),
        },
        {
            userId: 1,
            amount: 350.00,
            category: 'Transportation',
            merchant: 'Uber',
            date: new Date('2024-12-07').toISOString(),
            type: 'debit',
            description: 'Ride to airport',
            createdAt: new Date('2024-12-07').toISOString(),
        },
        {
            userId: 1,
            amount: 1500.00,
            category: 'Utilities',
            merchant: 'Airtel',
            date: new Date('2024-12-10').toISOString(),
            type: 'debit',
            description: 'Internet and phone bill',
            createdAt: new Date('2024-12-10').toISOString(),
        },
        {
            userId: 1,
            amount: 499.00,
            category: 'Entertainment',
            merchant: 'PlayStation Store',
            date: new Date('2024-12-12').toISOString(),
            type: 'debit',
            description: 'Game purchase',
            createdAt: new Date('2024-12-12').toISOString(),
        },
        {
            userId: 1,
            amount: 3500.00,
            category: 'Education',
            merchant: 'Udemy',
            date: new Date('2024-12-15').toISOString(),
            type: 'debit',
            description: 'Online course bundle',
            createdAt: new Date('2024-12-15').toISOString(),
        },
        {
            userId: 1,
            amount: 800.00,
            category: 'Food & Dining',
            merchant: 'McDonalds',
            date: new Date('2024-12-18').toISOString(),
            type: 'debit',
            description: 'Family meal',
            createdAt: new Date('2024-12-18').toISOString(),
        },
        {
            userId: 1,
            amount: 1800.00,
            category: 'Healthcare',
            merchant: 'Max Hospital',
            date: new Date('2024-12-20').toISOString(),
            type: 'debit',
            description: 'Health checkup',
            createdAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: 1,
            amount: 950.00,
            category: 'Transportation',
            merchant: 'BP Petrol Pump',
            date: new Date('2024-12-22').toISOString(),
            type: 'debit',
            description: 'Fuel refill',
            createdAt: new Date('2024-12-22').toISOString(),
        },
        {
            userId: 1,
            amount: 1500.00,
            category: 'Investment',
            merchant: 'Stock Dividend',
            date: new Date('2024-12-28').toISOString(),
            type: 'credit',
            description: 'Quarterly dividend',
            createdAt: new Date('2024-12-28').toISOString(),
        },
        
        // User 1 (Aarav Sharma) - January 2025
        {
            userId: 1,
            amount: 4500.00,
            category: 'Salary',
            merchant: 'Tech Solutions Pvt Ltd',
            date: new Date('2025-01-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2025-01-01').toISOString(),
        },
        {
            userId: 1,
            amount: 550.00,
            category: 'Food & Dining',
            merchant: 'Cafe Coffee Day',
            date: new Date('2025-01-03').toISOString(),
            type: 'debit',
            description: 'Weekend brunch',
            createdAt: new Date('2025-01-03').toISOString(),
        },
        {
            userId: 1,
            amount: 400.00,
            category: 'Transportation',
            merchant: 'Ola Cabs',
            date: new Date('2025-01-05').toISOString(),
            type: 'debit',
            description: 'Daily commute',
            createdAt: new Date('2025-01-05').toISOString(),
        },
        {
            userId: 1,
            amount: 1300.00,
            category: 'Utilities',
            merchant: 'Water Authority',
            date: new Date('2025-01-07').toISOString(),
            type: 'debit',
            description: 'Water and maintenance',
            createdAt: new Date('2025-01-07').toISOString(),
        },
        {
            userId: 1,
            amount: 600.00,
            category: 'Entertainment',
            merchant: 'PVR Cinemas',
            date: new Date('2025-01-10').toISOString(),
            type: 'debit',
            description: 'Movie tickets',
            createdAt: new Date('2025-01-10').toISOString(),
        },
        {
            userId: 1,
            amount: 8500.00,
            category: 'Electronics',
            merchant: 'Croma',
            date: new Date('2025-01-12').toISOString(),
            type: 'debit',
            description: 'Laptop accessories',
            createdAt: new Date('2025-01-12').toISOString(),
        },
        {
            userId: 1,
            amount: 750.00,
            category: 'Food & Dining',
            merchant: 'Subway',
            date: new Date('2025-01-15').toISOString(),
            type: 'debit',
            description: 'Lunch',
            createdAt: new Date('2025-01-15').toISOString(),
        },
        {
            userId: 1,
            amount: 650.00,
            category: 'Healthcare',
            merchant: 'Apollo Pharmacy',
            date: new Date('2025-01-18').toISOString(),
            type: 'debit',
            description: 'Medical supplies',
            createdAt: new Date('2025-01-18').toISOString(),
        },
        {
            userId: 1,
            amount: 900.00,
            category: 'Transportation',
            merchant: 'Shell Petrol',
            date: new Date('2025-01-20').toISOString(),
            type: 'debit',
            description: 'Fuel refill',
            createdAt: new Date('2025-01-20').toISOString(),
        },
        {
            userId: 1,
            amount: 2000.00,
            category: 'Investment',
            merchant: 'Fixed Deposit Interest',
            date: new Date('2025-01-25').toISOString(),
            type: 'credit',
            description: 'FD interest credit',
            createdAt: new Date('2025-01-25').toISOString(),
        },
        
        // User 2 (Priya Verma) - November 2024
        {
            userId: 2,
            amount: 5200.00,
            category: 'Salary',
            merchant: 'Design Studio Pvt Ltd',
            date: new Date('2024-11-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            userId: 2,
            amount: 850.00,
            category: 'Food & Dining',
            merchant: 'Mainland China',
            date: new Date('2024-11-04').toISOString(),
            type: 'debit',
            description: 'Dinner date',
            createdAt: new Date('2024-11-04').toISOString(),
        },
        {
            userId: 2,
            amount: 320.00,
            category: 'Transportation',
            merchant: 'Metro Card Recharge',
            date: new Date('2024-11-06').toISOString(),
            type: 'debit',
            description: 'Monthly metro pass',
            createdAt: new Date('2024-11-06').toISOString(),
        },
        {
            userId: 2,
            amount: 1400.00,
            category: 'Utilities',
            merchant: 'Electricity Board',
            date: new Date('2024-11-08').toISOString(),
            type: 'debit',
            description: 'Monthly electricity bill',
            createdAt: new Date('2024-11-08').toISOString(),
        },
        {
            userId: 2,
            amount: 999.00,
            category: 'Entertainment',
            merchant: 'Amazon Prime',
            date: new Date('2024-11-10').toISOString(),
            type: 'debit',
            description: 'Annual subscription',
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            userId: 2,
            amount: 3500.00,
            category: 'Education',
            merchant: 'Coursera',
            date: new Date('2024-11-13').toISOString(),
            type: 'debit',
            description: 'Professional certificate',
            createdAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 2,
            amount: 1200.00,
            category: 'Food & Dining',
            merchant: 'The Belgian Waffle Co',
            date: new Date('2024-11-16').toISOString(),
            type: 'debit',
            description: 'Dessert and coffee',
            createdAt: new Date('2024-11-16').toISOString(),
        },
        {
            userId: 2,
            amount: 2500.00,
            category: 'Healthcare',
            merchant: 'Fortis Hospital',
            date: new Date('2024-11-19').toISOString(),
            type: 'debit',
            description: 'Dental checkup',
            createdAt: new Date('2024-11-19').toISOString(),
        },
        {
            userId: 2,
            amount: 450.00,
            category: 'Transportation',
            merchant: 'Uber',
            date: new Date('2024-11-22').toISOString(),
            type: 'debit',
            description: 'Weekend ride',
            createdAt: new Date('2024-11-22').toISOString(),
        },
        {
            userId: 2,
            amount: 1800.00,
            category: 'Investment',
            merchant: 'SIP Returns',
            date: new Date('2024-11-27').toISOString(),
            type: 'credit',
            description: 'Monthly investment returns',
            createdAt: new Date('2024-11-27').toISOString(),
        },
        
        // User 2 (Priya Verma) - December 2024
        {
            userId: 2,
            amount: 5200.00,
            category: 'Salary',
            merchant: 'Design Studio Pvt Ltd',
            date: new Date('2024-12-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            userId: 2,
            amount: 1800.00,
            category: 'Food & Dining',
            merchant: 'Social Offline',
            date: new Date('2024-12-04').toISOString(),
            type: 'debit',
            description: 'Team lunch',
            createdAt: new Date('2024-12-04').toISOString(),
        },
        {
            userId: 2,
            amount: 280.00,
            category: 'Transportation',
            merchant: 'Rapido',
            date: new Date('2024-12-06').toISOString(),
            type: 'debit',
            description: 'Quick ride',
            createdAt: new Date('2024-12-06').toISOString(),
        },
        {
            userId: 2,
            amount: 1600.00,
            category: 'Utilities',
            merchant: 'Jio Fiber',
            date: new Date('2024-12-09').toISOString(),
            type: 'debit',
            description: 'Internet bill',
            createdAt: new Date('2024-12-09').toISOString(),
        },
        {
            userId: 2,
            amount: 1299.00,
            category: 'Entertainment',
            merchant: 'Disney+ Hotstar',
            date: new Date('2024-12-11').toISOString(),
            type: 'debit',
            description: 'Annual subscription',
            createdAt: new Date('2024-12-11').toISOString(),
        },
        {
            userId: 2,
            amount: 25000.00,
            category: 'Electronics',
            merchant: 'Apple Store',
            date: new Date('2024-12-14').toISOString(),
            type: 'debit',
            description: 'iPad purchase',
            createdAt: new Date('2024-12-14').toISOString(),
        },
        {
            userId: 2,
            amount: 950.00,
            category: 'Food & Dining',
            merchant: 'KFC',
            date: new Date('2024-12-17').toISOString(),
            type: 'debit',
            description: 'Family meal',
            createdAt: new Date('2024-12-17').toISOString(),
        },
        {
            userId: 2,
            amount: 800.00,
            category: 'Healthcare',
            merchant: 'MedPlus',
            date: new Date('2024-12-19').toISOString(),
            type: 'debit',
            description: 'Vitamins and supplements',
            createdAt: new Date('2024-12-19').toISOString(),
        },
        {
            userId: 2,
            amount: 380.00,
            category: 'Transportation',
            merchant: 'Uber',
            date: new Date('2024-12-21').toISOString(),
            type: 'debit',
            description: 'Shopping mall trip',
            createdAt: new Date('2024-12-21').toISOString(),
        },
        {
            userId: 2,
            amount: 2200.00,
            category: 'Investment',
            merchant: 'Dividend Income',
            date: new Date('2024-12-28').toISOString(),
            type: 'credit',
            description: 'Investment returns',
            createdAt: new Date('2024-12-28').toISOString(),
        },
        
        // User 2 (Priya Verma) - January 2025
        {
            userId: 2,
            amount: 5200.00,
            category: 'Salary',
            merchant: 'Design Studio Pvt Ltd',
            date: new Date('2025-01-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2025-01-01').toISOString(),
        },
        {
            userId: 2,
            amount: 720.00,
            category: 'Food & Dining',
            merchant: 'Pizza Hut',
            date: new Date('2025-01-04').toISOString(),
            type: 'debit',
            description: 'Weekend dinner',
            createdAt: new Date('2025-01-04').toISOString(),
        },
        {
            userId: 2,
            amount: 300.00,
            category: 'Transportation',
            merchant: 'Auto Rickshaw',
            date: new Date('2025-01-06').toISOString(),
            type: 'debit',
            description: 'Local travel',
            createdAt: new Date('2025-01-06').toISOString(),
        },
        {
            userId: 2,
            amount: 1500.00,
            category: 'Utilities',
            merchant: 'Vi Postpaid',
            date: new Date('2025-01-08').toISOString(),
            type: 'debit',
            description: 'Phone bill',
            createdAt: new Date('2025-01-08').toISOString(),
        },
        {
            userId: 2,
            amount: 750.00,
            category: 'Entertainment',
            merchant: 'BookMyShow',
            date: new Date('2025-01-11').toISOString(),
            type: 'debit',
            description: 'Concert tickets',
            createdAt: new Date('2025-01-11').toISOString(),
        },
        {
            userId: 2,
            amount: 4500.00,
            category: 'Education',
            merchant: 'LinkedIn Learning',
            date: new Date('2025-01-13').toISOString(),
            type: 'debit',
            description: 'Premium annual subscription',
            createdAt: new Date('2025-01-13').toISOString(),
        },
        {
            userId: 2,
            amount: 1100.00,
            category: 'Food & Dining',
            merchant: 'Haldirams',
            date: new Date('2025-01-16').toISOString(),
            type: 'debit',
            description: 'Snacks shopping',
            createdAt: new Date('2025-01-16').toISOString(),
        },
        {
            userId: 2,
            amount: 1200.00,
            category: 'Healthcare',
            merchant: 'Apollo Pharmacy',
            date: new Date('2025-01-19').toISOString(),
            type: 'debit',
            description: 'Monthly medicines',
            createdAt: new Date('2025-01-19').toISOString(),
        },
        {
            userId: 2,
            amount: 420.00,
            category: 'Transportation',
            merchant: 'Ola',
            date: new Date('2025-01-22').toISOString(),
            type: 'debit',
            description: 'Ride to friend place',
            createdAt: new Date('2025-01-22').toISOString(),
        },
        {
            userId: 2,
            amount: 2500.00,
            category: 'Investment',
            merchant: 'Mutual Fund Returns',
            date: new Date('2025-01-27').toISOString(),
            type: 'credit',
            description: 'Monthly SIP returns',
            createdAt: new Date('2025-01-27').toISOString(),
        },
        
        // User 3 (Rohit Patel) - November 2024
        {
            userId: 3,
            amount: 3800.00,
            category: 'Salary',
            merchant: 'Marketing Agency Ltd',
            date: new Date('2024-11-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2024-11-01').toISOString(),
        },
        {
            userId: 3,
            amount: 680.00,
            category: 'Food & Dining',
            merchant: 'Burger King',
            date: new Date('2024-11-05').toISOString(),
            type: 'debit',
            description: 'Quick lunch',
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            userId: 3,
            amount: 750.00,
            category: 'Transportation',
            merchant: 'HP Petrol Pump',
            date: new Date('2024-11-07').toISOString(),
            type: 'debit',
            description: 'Bike fuel',
            createdAt: new Date('2024-11-07').toISOString(),
        },
        {
            userId: 3,
            amount: 1100.00,
            category: 'Utilities',
            merchant: 'Electricity Board',
            date: new Date('2024-11-09').toISOString(),
            type: 'debit',
            description: 'Monthly electricity bill',
            createdAt: new Date('2024-11-09').toISOString(),
        },
        {
            userId: 3,
            amount: 399.00,
            category: 'Entertainment',
            merchant: 'Spotify',
            date: new Date('2024-11-12').toISOString(),
            type: 'debit',
            description: 'Premium subscription',
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            userId: 3,
            amount: 550.00,
            category: 'Food & Dining',
            merchant: 'Chai Point',
            date: new Date('2024-11-15').toISOString(),
            type: 'debit',
            description: 'Tea and snacks',
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            userId: 3,
            amount: 5500.00,
            category: 'Electronics',
            merchant: 'Flipkart',
            date: new Date('2024-11-18').toISOString(),
            type: 'debit',
            description: 'Headphones and accessories',
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            userId: 3,
            amount: 900.00,
            category: 'Healthcare',
            merchant: 'City Hospital',
            date: new Date('2024-11-21').toISOString(),
            type: 'debit',
            description: 'Doctor consultation',
            createdAt: new Date('2024-11-21').toISOString(),
        },
        {
            userId: 3,
            amount: 280.00,
            category: 'Transportation',
            merchant: 'Uber',
            date: new Date('2024-11-24').toISOString(),
            type: 'debit',
            description: 'Evening ride',
            createdAt: new Date('2024-11-24').toISOString(),
        },
        {
            userId: 3,
            amount: 800.00,
            category: 'Investment',
            merchant: 'PPF Interest',
            date: new Date('2024-11-28').toISOString(),
            type: 'credit',
            description: 'Interest credit',
            createdAt: new Date('2024-11-28').toISOString(),
        },
        
        // User 3 (Rohit Patel) - December 2024
        {
            userId: 3,
            amount: 3800.00,
            category: 'Salary',
            merchant: 'Marketing Agency Ltd',
            date: new Date('2024-12-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            userId: 3,
            amount: 1200.00,
            category: 'Food & Dining',
            merchant: 'Hard Rock Cafe',
            date: new Date('2024-12-05').toISOString(),
            type: 'debit',
            description: 'Weekend dinner',
            createdAt: new Date('2024-12-05').toISOString(),
        },
        {
            userId: 3,
            amount: 800.00,
            category: 'Transportation',
            merchant: 'Reliance Petrol',
            date: new Date('2024-12-08').toISOString(),
            type: 'debit',
            description: 'Fuel refill',
            createdAt: new Date('2024-12-08').toISOString(),
        },
        {
            userId: 3,
            amount: 1250.00,
            category: 'Utilities',
            merchant: 'BSNL Broadband',
            date: new Date('2024-12-10').toISOString(),
            type: 'debit',
            description: 'Internet bill',
            createdAt: new Date('2024-12-10').toISOString(),
        },
        {
            userId: 3,
            amount: 499.00,
            category: 'Entertainment',
            merchant: 'Xbox Game Pass',
            date: new Date('2024-12-13').toISOString(),
            type: 'debit',
            description: 'Gaming subscription',
            createdAt: new Date('2024-12-13').toISOString(),
        },
        {
            userId: 3,
            amount: 2500.00,
            category: 'Education',
            merchant: 'Skillshare',
            date: new Date('2024-12-16').toISOString(),
            type: 'debit',
            description: 'Creative courses',
            createdAt: new Date('2024-12-16').toISOString(),
        },
        {
            userId: 3,
            amount: 850.00,
            category: 'Food & Dining',
            merchant: 'Taco Bell',
            date: new Date('2024-12-19').toISOString(),
            type: 'debit',
            description: 'Late night snack',
            createdAt: new Date('2024-12-19').toISOString(),
        },
        {
            userId: 3,
            amount: 1500.00,
            category: 'Healthcare',
            merchant: 'Wellness Forever',
            date: new Date('2024-12-21').toISOString(),
            type: 'debit',
            description: 'Health supplements',
            createdAt: new Date('2024-12-21').toISOString(),
        },
        {
            userId: 3,
            amount: 350.00,
            category: 'Transportation',
            merchant: 'Rapido',
            date: new Date('2024-12-24').toISOString(),
            type: 'debit',
            description: 'Christmas party ride',
            createdAt: new Date('2024-12-24').toISOString(),
        },
        {
            userId: 3,
            amount: 1000.00,
            category: 'Investment',
            merchant: 'Dividend',
            date: new Date('2024-12-29').toISOString(),
            type: 'credit',
            description: 'Stock dividend',
            createdAt: new Date('2024-12-29').toISOString(),
        },
        
        // User 3 (Rohit Patel) - January 2025
        {
            userId: 3,
            amount: 3800.00,
            category: 'Salary',
            merchant: 'Marketing Agency Ltd',
            date: new Date('2025-01-01').toISOString(),
            type: 'credit',
            description: 'Monthly salary deposit',
            createdAt: new Date('2025-01-01').toISOString(),
        },
        {
            userId: 3,
            amount: 950.00,
            category: 'Food & Dining',
            merchant: 'Pizza Express',
            date: new Date('2025-01-05').toISOString(),
            type: 'debit',
            description: 'Family dinner',
            createdAt: new Date('2025-01-05').toISOString(),
        },
        {
            userId: 3,
            amount: 780.00,
            category: 'Transportation',
            merchant: 'Essar Petrol',
            date: new Date('2025-01-08').toISOString(),
            type: 'debit',
            description: 'Fuel refill',
            createdAt: new Date('2025-01-08').toISOString(),
        },
        {
            userId: 3,
            amount: 1150.00,
            category: 'Utilities',
            merchant: 'Water Department',
            date: new Date('2025-01-10').toISOString(),
            type: 'debit',
            description: 'Water bill',
            createdAt: new Date('2025-01-10').toISOString(),
        },
        {
            userId: 3,
            amount: 650.00,
            category: 'Entertainment',
            merchant: 'Inox Cinema',
            date: new Date('2025-01-13').toISOString(),
            type: 'debit',
            description: 'Movie night',
            createdAt: new Date('2025-01-13').toISOString(),
        },
        {
            userId: 3,
            amount: 12000.00,
            category: 'Electronics',
            merchant: 'Samsung Store',
            date: new Date('2025-01-15').toISOString(),
            type: 'debit',
            description: 'Smart watch purchase',
            createdAt: new Date('2025-01-15').toISOString(),
        },
        {
            userId: 3,
            amount: 720.00,
            category: 'Food & Dining',
            merchant: 'Costa Coffee',
            date: new Date('2025-01-18').toISOString(),
            type: 'debit',
            description: 'Coffee and pastry',
            createdAt: new Date('2025-01-18').toISOString(),
        },
        {
            userId: 3,
            amount: 580.00,
            category: 'Healthcare',
            merchant: 'NetMeds',
            date: new Date('2025-01-20').toISOString(),
            type: 'debit',
            description: 'Online medicine order',
            createdAt: new Date('2025-01-20').toISOString(),
        },
        {
            userId: 3,
            amount: 320.00,
            category: 'Transportation',
            merchant: 'Ola',
            date: new Date('2025-01-23').toISOString(),
            type: 'debit',
            description: 'Office commute',
            createdAt: new Date('2025-01-23').toISOString(),
        },
        {
            userId: 3,
            amount: 1200.00,
            category: 'Investment',
            merchant: 'SIP Returns',
            date: new Date('2025-01-28').toISOString(),
            type: 'credit',
            description: 'Monthly investment returns',
            createdAt: new Date('2025-01-28').toISOString(),
        },
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully - 90 transactions created across 3 users');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});